export type Scope = "K" | "M" | "KM";
export type AnswerValue = "yes" | "no" | "partial";
export type CatalogQuestion = { id: string; sectionId: string; label: string; scope: Scope };
export type CatalogSection = { id: string; title: string; lead: string; skipIf?: "no-design" | "one-person-org" };

export const SECTIONS: CatalogSection[] = [
  { id: "company", title: "Företagsinformation", lead: "Uppgifter om verksamheten och kontaktperson i kvalitets- och miljöfrågor." },
  { id: "1-3", title: "Avsnitt 1–3 Omfattning", lead: "Tolka kraven efter verksamheten. Beskriv hur företaget fungerar idag, lägg sedan till det som saknas." },
  { id: "4.1", title: "Avsnitt 4.1–4.2 Processer och manual", lead: "Skapa processer för hur företaget fungerar. Visa samverkan, t.ex. i en huvudprocessbild." },
  { id: "4.2.3", title: "Avsnitt 4.2.3–4.2.4 Styrning av dokument", lead: "Samla mallar, avtal, lagar och checklistor." },
  { id: "5.1", title: "Avsnitt 5.1 Åtagande", lead: "Ledningen tar sitt ansvar skriftligen." },
  { id: "5.2", title: "Avsnitt 5.2 Kundkrav och miljöaspekter", lead: "Vad kunden vill ha, och vilka miljöaspekter ni kan påverka." },
  { id: "5.3", title: "Avsnitt 5.3 Policy", lead: "Policyn ska vara vägledande för medarbetarna och för målen." },
  { id: "5.4", title: "Avsnitt 5.4 Mål", lead: "Mål ska vara mätbara, tidsbestämda och i linje med policyn." },
  { id: "5.5", title: "Avsnitt 5.5 Organisation och kommunikation", lead: "Enmansföretag kan bortse från organisationsschema." },
  { id: "5.6", title: "Avsnitt 5.6 Ledningens genomgång", lead: "Ledningens genomgång av ledningssystemet." },
  { id: "6", title: "Avsnitt 6 Resurser och kompetens", lead: "Samla kompetens, utbildning, betyg och referenser per person." },
  { id: "7.1", title: "Avsnitt 7.1–7.2 Kundrelaterade processer", lead: "Offert, order, avtal och kundkrav." },
  { id: "7.3", title: "Avsnitt 7.3 Konstruktion och utveckling", lead: "Hoppa över om verksamheten inte konstruerar.", skipIf: "no-design" },
  { id: "7.4", title: "Avsnitt 7.4 Inköp", lead: "Bedömning av leverantörer och inköpskrav." },
  { id: "7.5", title: "Avsnitt 7.5 Produktion och tjänsteutövning", lead: "Produktion, identifiering, kundens egendom, hantering och skydd." },
  { id: "7.6", title: "Avsnitt 7.6 Mätutrustning", lead: "Kalibrerade mätdon och spårbarhet." },
  { id: "8", title: "Avsnitt 8 Mätning, avvikelse och förbättring", lead: "Revisioner, kundmätningar, reklamationer och avvikelser." },
];

export const QUESTIONS: CatalogQuestion[] = [
  { id: "1-3.scope-whole", sectionId: "1-3", label: "Kvalitets- och miljösäkring gäller hela företaget", scope: "KM" },
  { id: "1-3.multi-company", sectionId: "1-3", label: "Flera bolag ska omfattas av ledningssystemet", scope: "KM" },
  { id: "1-3.design", sectionId: "1-3", label: "Konstruktion/utveckling bedrivs (annars kan 7.3 uteslutas)", scope: "K" },
  { id: "1-3.association", sectionId: "1-3", label: "Vi är med i organisation vars stadgar ska följas", scope: "KM" },
  { id: "1-3.ama-consumer", sectionId: "1-3", label: "Krav på AMA, konsumentköp- eller konsumenttjänstlagen", scope: "K" },
  { id: "1-3.env-law", sectionId: "1-3", label: "Vi följer miljölagstiftning och ev. tillstånd/anmälan", scope: "M" },
  { id: "4.1.documented-system", sectionId: "4.1", label: "Dokumenterat kvalitets- eller miljösystem", scope: "KM" },
  { id: "4.1.processes", sectionId: "4.1", label: "Nödvändiga processer identifierade (även UE)", scope: "KM" },
  { id: "4.1.flowcharts", sectionId: "4.1", label: "Flödesscheman anpassade efter verksamheten", scope: "KM" },
  { id: "4.1.manual-digital", sectionId: "4.1", label: "Manual förvaras digitalt / i dokumentstyrningsprogram", scope: "KM" },
  { id: "4.1.manual-binder", sectionId: "4.1", label: "Manual i pärmform", scope: "KM" },
  { id: "4.1.manual-access", sectionId: "4.1", label: "Medarbetare har åtkomst till manualen", scope: "KM" },
  { id: "4.2.3.template-control", sectionId: "4.2.3", label: "Dokumenterad rutin för styrning av mallar", scope: "KM" },
  { id: "4.2.3.right-version", sectionId: "4.2.3", label: "Rätt version tillgänglig", scope: "KM" },
  { id: "4.2.3.obsolete", sectionId: "4.2.3", label: "Föråldrade dokument kan inte användas oavsiktligt", scope: "KM" },
  { id: "4.2.3.create-docs", sectionId: "4.2.3", label: "Rutin för upprättande av dokument", scope: "KM" },
  { id: "4.2.3.revise", sectionId: "4.2.3", label: "Rutin vid revidering av dokument och data", scope: "KM" },
  { id: "4.2.3.archive", sectionId: "4.2.3", label: "Arkiveringsrutiner", scope: "KM" },
  { id: "4.2.3.doc-list", sectionId: "4.2.3", label: "Förteckning över dokument", scope: "KM" },
  { id: "4.2.3.law-list", sectionId: "4.2.3", label: "Aktuell laglista", scope: "M" },
  { id: "5.1.staff-meeting", sectionId: "5.1", label: "Personalmöte", scope: "KM" },
  { id: "5.1.appraisal", sectionId: "5.1", label: "Medarbetarsamtal", scope: "KM" },
  { id: "5.1.project-meeting", sectionId: "5.1", label: "Projektmöte", scope: "KM" },
  { id: "5.1.planning-meeting", sectionId: "5.1", label: "Planeringsmöte", scope: "KM" },
  { id: "5.1.monthly-meeting", sectionId: "5.1", label: "Månadsmöte", scope: "KM" },
  { id: "5.1.mgmt-review", sectionId: "5.1", label: "Ledningens genomgång", scope: "KM" },
  { id: "5.1.agenda", sectionId: "5.1", label: "Agenda vid möten", scope: "KM" },
  { id: "5.1.minutes", sectionId: "5.1", label: "Protokoll förs", scope: "KM" },
  { id: "5.1.resources", sectionId: "5.1", label: "Ledningen avsätter tillräckliga resurser", scope: "KM" },
  { id: "5.1.roles", sectionId: "5.1", label: "Roller, ansvar och befogenheter dokumenterade", scope: "KM" },
  { id: "5.2.customer-understood", sectionId: "5.2", label: "Rutin för att kundkrav är förstådda", scope: "K" },
  { id: "5.2.customer-fulfilled", sectionId: "5.2", label: "Rutin för att kundkrav uppfylls och kundtillfredsställelse ökar", scope: "K" },
  { id: "5.2.legal", sectionId: "5.2", label: "Rutin för tillämpliga lagkrav för företag, kund och leverantör", scope: "KM" },
  { id: "5.2.aspects-id", sectionId: "5.2", label: "Rutiner för att identifiera miljöaspekter", scope: "M" },
  { id: "5.2.aspects-significant", sectionId: "5.2", label: "Rutiner för att avgöra betydande aspekter", scope: "M" },
  { id: "5.2.aspects-law", sectionId: "5.2", label: "Rutiner för hur lagkrav tillämpas på miljöaspekterna", scope: "M" },
  { id: "5.2.law-list", sectionId: "5.2", label: "Aktuell laglista", scope: "M" },
  { id: "5.2.sds", sectionId: "5.2", label: "Säkerhetsdatablad för kemikalier/produkter", scope: "M" },
  { id: "5.2.env-review", sectionId: "5.2", label: "Miljöutredning", scope: "M" },
  { id: "5.3.q-policy", sectionId: "5.3", label: "Skriftlig kvalitetspolicy", scope: "K" },
  { id: "5.3.e-policy", sectionId: "5.3", label: "Skriftlig miljöpolicy", scope: "M" },
  { id: "5.3.known", sectionId: "5.3", label: "Policy känd och accepterad", scope: "KM" },
  { id: "5.3.understood", sectionId: "5.3", label: "Personalen har förstått innebörden", scope: "KM" },
  { id: "5.3.public", sectionId: "5.3", label: "Miljöpolicy tillgänglig för allmänheten", scope: "M" },
  { id: "5.3.improve", sectionId: "5.3", label: "Åtagande om ständig förbättring och förebyggande av förorening", scope: "M" },
  { id: "5.3.comply", sectionId: "5.3", label: "Åtagande att följa lagar och andra krav", scope: "KM" },
  { id: "5.3.review", sectionId: "5.3", label: "Policy granskas och revideras vid behov", scope: "KM" },
  { id: "5.4.env-goal", sectionId: "5.4", label: "Skriftligt miljömål", scope: "M" },
  { id: "5.4.q-goal", sectionId: "5.4", label: "Skriftligt kvalitetsmål", scope: "K" },
  { id: "5.4.product-req", sectionId: "5.4", label: "Målen beaktar krav på varor och tjänster", scope: "K" },
  { id: "5.4.measurable", sectionId: "5.4", label: "Målen är mätbara och tidsbestämda", scope: "KM" },
  { id: "5.4.env-overall", sectionId: "5.4", label: "Övergripande miljömål dokumenterade och underhållna", scope: "M" },
  { id: "5.4.env-aligned", sectionId: "5.4", label: "Miljömål i linje med miljöpolicy", scope: "M" },
  { id: "5.4.q-aligned", sectionId: "5.4", label: "Kvalitetsmål i linje med kvalitetspolicy", scope: "K" },
  { id: "5.4.plans", sectionId: "5.4", label: "Handlingsplaner för att nå målen", scope: "KM" },
  { id: "5.5.org-chart", sectionId: "5.5", label: "Organisationsschema, känt bland personal", scope: "KM" },
  { id: "5.5.job-desc", sectionId: "5.5", label: "Befattningsbeskrivningar", scope: "KM" },
  { id: "5.5.deputy", sectionId: "5.5", label: "Utnämnd ersättare", scope: "KM" },
  { id: "5.5.authority", sectionId: "5.5", label: "Beskrivning av ansvar och befogenheter", scope: "KM" },
  { id: "5.5.comms", sectionId: "5.5", label: "Kommunikation (sms, telefon, e-post, internet, hemsida)", scope: "KM" },
  { id: "5.5.rep", sectionId: "5.5", label: "Ledningens representant för kvalitets- och miljöfrågor", scope: "KM" },
  { id: "5.5.resources", sectionId: "5.5", label: "Resurser tilldelade, protokoll finns", scope: "KM" },
  { id: "5.5.external", sectionId: "5.5", label: "Beslut om hur miljöaspekter och policy kommuniceras utåt", scope: "M" },
  { id: "5.6.held", sectionId: "5.6", label: "Ledningens genomgång genomförs", scope: "KM" },
  { id: "5.6.agenda", sectionId: "5.6", label: "Agenda för möten", scope: "KM" },
  { id: "5.6.minutes", sectionId: "5.6", label: "Protokoll över beslut", scope: "KM" },
  { id: "5.6.archive", sectionId: "5.6", label: "Protokoll arkiveras", scope: "KM" },
  { id: "5.6.input", sectionId: "5.6", label: "Underlag för beslut är fastlagt", scope: "KM" },
  { id: "6.resource-routines", sectionId: "6", label: "Rutiner för resurstilldelning", scope: "KM" },
  { id: "6.resource-eval", sectionId: "6", label: "Resurstilldelningen utvärderas", scope: "KM" },
  { id: "6.training-need", sectionId: "6", label: "Nedskrivna rutiner för utbildningsbehov", scope: "KM" },
  { id: "6.intro", sectionId: "6", label: "Introduktionsutbildning för nyanställda", scope: "KM" },
  { id: "6.development", sectionId: "6", label: "Utvecklingssamtal", scope: "KM" },
  { id: "6.matrix", sectionId: "6", label: "Kompetensmatris", scope: "KM" },
  { id: "6.plans", sectionId: "6", label: "Utbildningsplaner", scope: "KM" },
  { id: "6.records", sectionId: "6", label: "Dokumentation av utbildning bevaras", scope: "KM" },
  { id: "6.followup", sectionId: "6", label: "Genomförda utbildningar följs upp", scope: "KM" },
  { id: "6.practical", sectionId: "6", label: "Praktisk utbildning eller andra åtgärder genomförda", scope: "KM" },
  { id: "7.1.offer", sectionId: "7.1", label: "Rutin för offert, order och avtal", scope: "K" },
  { id: "7.1.review", sectionId: "7.1", label: "Kundkrav granskas innan åtagande", scope: "K" },
  { id: "7.1.changes", sectionId: "7.1", label: "Ändringar kommuniceras", scope: "K" },
  { id: "7.3.plan", sectionId: "7.3", label: "Planering av konstruktion/utveckling", scope: "K" },
  { id: "7.3.io", sectionId: "7.3", label: "Indata och utdata styrs", scope: "K" },
  { id: "7.3.verify", sectionId: "7.3", label: "Granskning, verifiering och validering", scope: "K" },
  { id: "7.3.eval", sectionId: "7.3", label: "Resultat kan utvärderas mot ställda krav", scope: "K" },
  { id: "7.3.env", sectionId: "7.3", label: "Miljökrav beaktas i konstruktion", scope: "M" },
  { id: "7.4.assess", sectionId: "7.4", label: "Leverantörer bedöms och godkänns", scope: "KM" },
  { id: "7.4.list", sectionId: "7.4", label: "Förteckning över godkända leverantörer och produkter", scope: "K" },
  { id: "7.4.packaging", sectionId: "7.4", label: "Specifika krav på emballage", scope: "KM" },
  { id: "7.4.certs", sectionId: "7.4", label: "Materialintyg från leverantör vid behov", scope: "K" },
  { id: "7.4.env", sectionId: "7.4", label: "Miljökrav på leverantörer", scope: "M" },
  { id: "7.5.flow", sectionId: "7.5", label: "Flödesschema över produktionsförloppet", scope: "K" },
  { id: "7.5.workorder", sectionId: "7.5", label: "Arbetsorder", scope: "K" },
  { id: "7.5.instructions", sectionId: "7.5", label: "Arbetsinstruktioner på arbetsplatsen", scope: "K" },
  { id: "7.5.maintenance", sectionId: "7.5", label: "Underhåll av maskiner och maskininstruktioner", scope: "K" },
  { id: "7.5.selfcheck", sectionId: "7.5", label: "Egenkontroll och rutiner för kontrollmetoder", scope: "K" },
  { id: "7.5.final", sectionId: "7.5", label: "Slutkontroll före leverans", scope: "K" },
  { id: "7.5.records", sectionId: "7.5", label: "Kontrollistor/protokoll arkiveras", scope: "K" },
  { id: "7.5.trace", sectionId: "7.5", label: "Identifikation och spårbarhet i produktion och efter leverans", scope: "K" },
  { id: "7.5.unique-id", sectionId: "7.5", label: "Entydig identifikation per produkt/tjänst", scope: "K" },
  { id: "7.5.pack-info", sectionId: "7.5", label: "Förpackningar upplyser om innehåll", scope: "KM" },
  { id: "7.5.nonconforming", sectionId: "7.5", label: "Regler för avvikande produkter", scope: "K" },
  { id: "7.5.transport-id", sectionId: "7.5", label: "Identifierbarhet under transport", scope: "K" },
  { id: "7.5.order-system", sectionId: "7.5", label: "Dataprogram där order kan spåras", scope: "K" },
  { id: "7.5.customer-property", sectionId: "7.5", label: "Rutiner för kundens egendom", scope: "K" },
  { id: "7.5.customer-loss", sectionId: "7.5", label: "Rapport till kund vid förlust/skada", scope: "K" },
  { id: "7.5.customer-separate", sectionId: "7.5", label: "Kundens egendom märks och förvaras avskilt", scope: "K" },
  { id: "7.5.nda", sectionId: "7.5", label: "Sekretessavtal där det krävs", scope: "K" },
  { id: "7.5.fifo", sectionId: "7.5", label: "FIFO", scope: "K" },
  { id: "7.5.damage", sectionId: "7.5", label: "Förvaring och hantering förhindrar skada", scope: "KM" },
  { id: "7.5.packaging", sectionId: "7.5", label: "Lämpligt emballage internt och externt", scope: "KM" },
  { id: "7.5.delivery", sectionId: "7.5", label: "Rutiner för leverans och transportinstruktioner", scope: "K" },
  { id: "7.5.protect", sectionId: "7.5", label: "Skydd under hela tillverkningen", scope: "K" },
  { id: "7.5.warehouse", sectionId: "7.5", label: "Rutin för lagerhantering", scope: "K" },
  { id: "7.5.chemicals", sectionId: "7.5", label: "Kemikaliehantering, spill och avfall", scope: "M" },
  { id: "7.6.calibrated", sectionId: "7.6", label: "Endast kalibrerade mätdon används", scope: "K" },
  { id: "7.6.interval", sectionId: "7.6", label: "Kalibrering enligt tidsintervall", scope: "K" },
  { id: "7.6.records", sectionId: "7.6", label: "Resultat dokumenteras och bevaras", scope: "K" },
  { id: "7.6.trace", sectionId: "7.6", label: "Spårbarhet till nationella/internationella normaler", scope: "K" },
  { id: "7.6.protect", sectionId: "7.6", label: "Skydd mot skada vid hantering och förvaring", scope: "K" },
  { id: "7.6.marked", sectionId: "7.6", label: "Kalibreringspliktig utrustning är uppmärkt", scope: "K" },
  { id: "8.internal-audit", sectionId: "8", label: "Interna revisioner", scope: "KM" },
  { id: "8.customer-measure", sectionId: "8", label: "Kundmätningar", scope: "K" },
  { id: "8.customer-fulfilled", sectionId: "8", label: "Rutin för att ta reda på om kundkrav uppfyllts", scope: "K" },
  { id: "8.methods", sectionId: "8", label: "Metoder för mätning, analys och förbättring beslutade", scope: "KM" },
  { id: "8.auditor", sectionId: "8", label: "Utsedd internrevisor med tillräcklig utbildning", scope: "KM" },
  { id: "8.audit-plan", sectionId: "8", label: "Revisionsplan och revisionsprogram", scope: "KM" },
  { id: "8.audit-archive", sectionId: "8", label: "Revisionsresultat arkiveras", scope: "KM" },
  { id: "8.goods-in", sectionId: "8", label: "Rutin för godsmottagning", scope: "K" },
  { id: "8.in-process", sectionId: "8", label: "Rutin för kontroll under produktion", scope: "K" },
  { id: "8.final", sectionId: "8", label: "Rutin för slutkontroll", scope: "K" },
  { id: "8.monitor-product", sectionId: "8", label: "Metoder för att övervaka att produktegenskaper når kundkrav", scope: "K" },
  { id: "8.ncr", sectionId: "8", label: "Rutin för avvikelseutredning", scope: "KM" },
  { id: "8.ncr-isolate", sectionId: "8", label: "Avvikande produkter rapporteras, sammanställs och avskiljs", scope: "K" },
  { id: "8.ncr-records", sectionId: "8", label: "Dokumentation om avvikelser och åtgärder bevaras", scope: "KM" },
  { id: "8.env-accident", sectionId: "8", label: "Rutin vid miljöolyckor", scope: "M" },
  { id: "8.emergency-id", sectionId: "8", label: "Identifiering av nödlägen och olyckor", scope: "M" },
  { id: "8.emergency-act", sectionId: "8", label: "Rutin för agerande vid nödläge", scope: "M" },
  { id: "8.corrective", sectionId: "8", label: "Korrigerande åtgärder, dokumenteras och granskas", scope: "KM" },
  { id: "8.preventive", sectionId: "8", label: "Förebyggande åtgärder, dokumenteras, utvärderas och följs upp", scope: "KM" },
  { id: "8.preventive-mgmt", sectionId: "8", label: "Förebyggande åtgärder rapporteras till ledningen", scope: "KM" },
  { id: "8.improve", sectionId: "8", label: "Förbättringsverksamhet / förslagsverksamhet", scope: "KM" },
];

export const COMPANY_FIELDS = [
  "Företagets namn", "Organisationsnummer", "Adress", "Postnummer och ort", "Besöksadress", "Mobil", "Hemsida", "E-post", "Kommun / län", "Kontaktperson i kvalitets- och miljöfrågor", "Mobil / e-post kontaktperson", "Antal anställda (män / kvinnor)", "System som ska ingå", "Certifiering idag / mål",
] as const;
